export const mockData = [
    {
        id: 1,
        rut: '12.345.678-9',
        nombre: 'Juan Perez',
        departamento: 'Informática',
        fechaDesde: '01-08-2024',
        fechaHasta: '05-08-2024',
        jornada: 'Completa',
        duracion: 5,
        fechaSolicitud: '15-07-2024',
        tipoSolicitud: 'Feriado Legal',
        contrato: 'Planta',
        documento: 'documento1.pdf'
    },
    {
        id: 2,
        rut: '98.765.432-1',
        nombre: 'Maria Rodriguez',
        departamento: 'Recursos Humanos',
        fechaDesde: '10-08-2024',
        fechaHasta: '12-08-2024',
        jornada: 'Media Jornada',
        duracion: 2.5,
        fechaSolicitud: '20-07-2024',
        tipoSolicitud: 'Permiso Administrativo',
        contrato: 'Contrata',
        documento: 'documento2.pdf'
    },
    {
        id: 3,
        rut: '11.222.333-4',
        nombre: 'Pedro Gomez',
        departamento: 'Finanzas',
        fechaDesde: '15-08-2024',
        fechaHasta: '20-08-2024',
        jornada: 'Completa',
        duracion: 6,
        fechaSolicitud: '01-08-2024',
        tipoSolicitud: 'Feriado Legal',
        contrato: 'Planta',
        documento: 'documento3.pdf'
    },
    {
        id: 4,
        rut: '22.333.444-5',
        nombre: 'Ana Martinez',
        departamento: 'Operaciones',
        fechaDesde: '02-09-2024',
        fechaHasta: '03-09-2024',
        jornada: 'Completa',
        duracion: 2,
        fechaSolicitud: 'Permiso Administrativo',
        contrato: 'Suplencia',
        documento: 'documento4.pdf'
    },
    {
        id: 5,
        rut: '13.456.789-0',
        nombre: 'Carlos Sanchez',
        departamento: 'Informática',
        fechaDesde: '05-09-2024',
        fechaHasta: '10-09-2024',
        jornada: 'Completa',
        duracion: 6,
        fechaSolicitud: '20-08-2024',
        tipoSolicitud: 'Feriado Legal',
        contrato: 'Planta',
        documento: 'documento5.pdf'
    },
    {
        id: 7,
        rut: '15.678.901-2',
        nombre: 'Jorge Diaz',
        departamento: 'Finanzas',
        fechaDesde: '19-09-2024',
        fechaHasta: '23-09-2024',
        jornada: 'Completa',
        duracion: 5,
        fechaSolicitud: '01-09-2024',
        tipoSolicitud: 'Feriado Legal',
        contrato: 'Planta',
        documento: 'documento7.pdf'
    },
    {
        id: 8,
        rut: '16.789.012-3',
        nombre: 'Sofia Castro',
        departamento: 'Recursos Humanos',
        fechaDesde: '26-09-2024',
        fechaHasta: '27-09-2024',
        jornada: 'Completa',
        duracion: 2,
        fechaSolicitud: 'Permiso Administrativo',
        contrato: 'Contrata',
        documento: 'documento8.pdf'
    },
    {
        id: 9,
        rut: '17.890.123-4',
        nombre: 'Matias Torres',
        departamento: 'Operaciones',
        fechaDesde: '30-09-2024',
        fechaHasta: '04-10-2024',
        jornada: 'Completa',
        duracion: 5,
        fechaSolicitud: '15-09-2024',
        tipoSolicitud: 'Feriado Legal',
        contrato: 'Suplencia',
        documento: 'documento9.pdf'
    },
    {
        id: 10,
        rut: '18.901.234-5',
        nombre: 'Camila Herrera',
        departamento: 'Informática',
        fechaDesde: '07-10-2024',
        fechaHasta: '11-10-2024',
        jornada: 'Completa',
        duracion: 5,
        fechaSolicitud: '20-09-2024',
        tipoSolicitud: 'Feriado Legal',
        contrato: 'Planta',
        documento: 'documento10.pdf'
    },
    {
        id: 12,
        rut: '20.123.456-7',
        nombre: 'Valentina Rojas',
        departamento: 'Finanzas',
        fechaDesde: '21-10-2024',
        fechaHasta: '22-10-2024',
        jornada: 'Media Jornada',
        duracion: 1,
        fechaSolicitud: '05-10-2024',
        tipoSolicitud: 'Permiso Administrativo',
        contrato: 'Contrata',
        documento: 'documento12.pdf'
    },
    {
        id: 13,
        rut: '21.234.567-8',
        nombre: 'Francisco Soto',
        departamento: 'Operaciones',
        fechaDesde: '25-10-2024',
        fechaHasta: '28-10-2024',
        jornada: 'Completa',
        duracion: 4,
        fechaSolicitud: '10-10-2024',
        tipoSolicitud: 'Feriado Legal',
        contrato: 'Planta',
        documento: 'documento13.pdf'
    },
    {
        id: 14,
        rut: '22.345.678-9',
        nombre: 'Daniela Perez',
        departamento: 'Informática',
        fechaDesde: '01-11-2024',
        fechaHasta: '05-11-2024',
        jornada: 'Completa',
        duracion: 5,
        fechaSolicitud: '15-10-2024',
        tipoSolicitud: 'Permiso Administrativo',
        contrato: 'Suplencia',
        documento: 'documento14.pdf'
    }
];